[project]
name = "gst-tally"
version = "0.0.1"
description = "Convert WooCommerce CSV exports to Tally XML format with GST calculations"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
dependencies = []
